DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hayel_app') THEN
    CREATE ROLE hayel_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO hayel_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON organizations, users, employees, employments TO hayel_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO hayel_app;
